
VAMPSDK_DIR	:= ../vamp-plugin-sdk

ARCHFLAGS 	:= -mmacosx-version-min=10.6

CXXFLAGS	:= -Wall -Wextra -Werror -I$(VAMPSDK_DIR) -g -fPIC $(ARCHFLAGS)

PLUGIN_LDFLAGS	:= -dynamiclib $(ARCHFLAGS) $(VAMP_SDK_DIR)/libvamp-sdk.a -exported_symbols_list vamp-plugin.list -install_name $(PLUGIN_LIBRARY_NAME)$(PLUGIN_EXT)

PLUGIN_EXT	:= .dylib

MAKEFILE_EXT 	:= .osx

include Makefile.inc

