
VAMPSDK_DIR	:= ../vamp-plugin-sdk

CXX	        := i486-mingw32-c++

CXXFLAGS	:= -Wall -Wextra -Werror -I$(VAMPSDK_DIR) -g -fPIC $(ARCHFLAGS)

PLUGIN_LDFLAGS	:= -shared -Wl,-soname=$(PLUGIN_LIBRARY_NAME)$(PLUGIN_EXT) -Wl,-Bstatic -L$(VAMPSDK_DIR) -lvamp-sdk -Wl,-Bdynamic -Wl,--retain-symbols-file=vamp-plugin.list

PLUGIN_EXT	:= .dll

MAKEFILE_EXT 	:= .mingw32

include Makefile.inc

